### ISSUE TITLE
[README.md] <Some typos in the last line of the README.md file >

### ISSUE THREAD

**Issue by codewithrabeeh** [IAmTamal/Milan#340]
### Description

There's no space between  "Thankyou", which is situated in the last line of the readme file.

**Comment by IAmTamal** [comment]
<h1>It's great having you contribute to Milan !</h1> This is an <b>auto-generated</b> text<p>The <b>maintainers/owner</b> will look into the issue soon, add relevant tags and proceed further, please have paitence. Meanwhile feel free to support <b>star the repo</b> and <b>share it</b> with your friends. :nerd_face: :rocket:</p>

**Comment by codewithrabeeh** [comment]
Actually, I intended to do this for Hactoberfest'22. Although you did it. Go ahead!

**Comment by IAmTamal** [comment]
Hello @codewithrabeeh , @aharna  - i am closing this issue because this is what `hacktoberfest` technically defines as spam. If i add the `spam` label chances are you'd be banned from Hacktoberfest. The word can be written as `Thank you` and `Thankyou` - either way it is the same.

Anyways look for other issues to contribute.
Star the repo to get quick updates.

Regards,
Tamal

**Comment by codewithrabeeh** [comment]
> Hello @codewithrabeeh , @aharna  - i am closing this issue because this is what `hacktoberfest` technically defines as spam. If i add the `spam` label chances are you'd be banned from Hacktoberfest. The word can be written as `Thank you` and `Thankyou` - either way it is the same.
> 
> Anyways look for other issues to contribute.
> Star the repo to get quick updates.
> 
> Regards,
> Tamal

Oh, sorry. My mistake.
