### ISSUE TITLE
[DOCS] Add automatic release

### ISSUE THREAD

**Issue by Dun-sin** [IAmTamal/Milan#506]
### Description

I noticed that the releases are done manually
How about create an automatic release, that happens whenever some contributes to this project, it will use the conventional commit. I see you already use conventional commits.

Here's a link for reference: 
[Set Automatic Release (Skip Commitizen)](https://youtu.be/QZdY4XYbqLI)

### Additional information

> ## This can only be done by the owner of the repo

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)

**Comment by IAmTamal** [comment]
Hello Dunsin 
 - Can you please let me know what exactly is meant by `releases are done manually` ? 
 - I am not able to understand the concept of automating the release.
 - My releases are manually rolled out because i want to roll out a release only when there's some significant changes
 - The release notes are however automated , we track the labels and then based on those labels we put it under "Bug fixes" , "Features" etc

**Comment by Dun-sin** [comment]
> Hello Dunsin
> 
>     * Can you please let me know what exactly is meant by `releases are done manually` ?
> 
>     * I am not able to understand the concept of automating the release.
> 
>     * My releases are manually rolled out because i want to roll out a release only when there's some significant changes
> 
>     * The release notes are however automated , we track the labels and then based on those labels we put it under "Bug fixes" , "Features" etc

alright if that's your choice
