### ISSUE TITLE
[CHORE] Improve footer layout

### ISSUE THREAD

**Issue by rupali-codes** [IAmTamal/Milan#623]
### What would you like to share?

Currently, the footer is having too much gap between the elements, and it looks kinda empty, it would lead to such a nice user experience if we can improve the layout a bit.

### Suggestions
 - Add `Milan` icon in `contribute` section
 - Shift `Join us` links and `Report` section to right
 - Make footer a bit _darker_ 
 - Make GitHub logo _bright_

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by Deva-1903** [comment]
Can I work on this issue?

**Comment by Saurav-Pant** [comment]
is anyone working on this issue, if not Please assign it to me

**Comment by IAmTamal** [comment]
> I inquired four days in advance whether it was available for work, and if so, please assign it to me.

Hi @Deva-1903 , to solve confusion like this,  we have a checkbox for the person who is raising the issue. It's clearly written to `tick the box` if they want to work on the issue. 

Since they have done so, I assigned them. If they don't want to, I'll assign you. 
Thanks.


![image](https://user-images.githubusercontent.com/72851613/231823985-37b1fd90-1b40-49c7-a212-e53838117de0.png)

**Comment by Deva-1903** [comment]
Sorry, I missed it. I appreciate your saying @IAmTamal

**Comment by rupali-codes** [comment]
Hey @IAmTamal thanks for assigning, will rise the PR soon

**Comment by rupali-codes** [comment]
Whoops, i'm sorry i was totally forgot about this, i'll rise the PR today by evening :)

**Comment by jayk-gupta** [comment]
Also the background color could be changed according to the theme, may be light red.
Let me know if I can contribute anything to it.
