### ISSUE TITLE
[BUG] write a small description here

### ISSUE THREAD

**Issue by priyankarpal** [IAmTamal/Milan#635]
### Description

Links do not have a discernible name

We need to add alt text, link text to fix this error(if I'm not wrong)

### Screenshots

![Screenshot from 2023-04-15 20-53-34](https://user-images.githubusercontent.com/88102392/232233999-ec75935d-8b8e-4487-871e-3516829142a6.png)

### Browser 🥦

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [ ] I am willing to work on this issue (blank for no)

**Comment by raghav1030** [comment]
can you please specify , which all links proposed this problem?

**Comment by raghav1030** [comment]
Acc. to me we have to give proper descriptive phrases for the links that could be easily understood by the screen readers like if we want to add a link for downloading a pdf then rather than giving the title as "Click here" we can give it as "Download the PDF file".
So it would be feasible if we get the data for the links that are causing this problems ig?

**Comment by priyankarpal** [comment]
> Acc. to me we have to give proper descriptive phrases for the links that could be easily understood by the screen readers like if we want to add a link for downloading a pdf then rather than giving the title as "Click here" we can give it as "Download the PDF file". So it would be feasible if we get the data for the links that are causing this problems ig?

yes. I'm also thinking

**Comment by IAmTamal** [comment]
Great issue, @priyankarpal  - the thing is in order to make the links more accessible we need to add those texts such as `<a aria-describedby=”foo”>Some link text”</a>` , and also `tabindex=”0”` so that it is more focusable on the keyboards.

Here's a documentation you can learn :  [Links | Accessibility, Usage](https://usability.yale.edu/web-accessibility/articles/links)

**Comment by priyankarpal** [comment]
I want to work on this issue.

**Comment by CBID2** [comment]
Which file has this problem?
