### ISSUE TITLE
[DOCS] Razorpay documentation variables mismatch

### ISSUE THREAD

**Issue by tejaskh3** [IAmTamal/Milan#665]
### Description

While setting up backend locally even after providing key and secret I was getting error then checked variable name used in docs are different from actual one.

### Name in docs 
<img width="523" alt="image" src="https://user-images.githubusercontent.com/98630752/236725837-df611d84-87ab-4997-a6af-ccc8fd609207.png">

### Actual name
<img width="231" alt="image" src="https://user-images.githubusercontent.com/98630752/236726361-dc37678f-9180-4593-be33-3280d7ea081f.png">

### 🥦 Browser

Brave

### Checklist ✅

- [X] I checked and didn't find similar issue
- [X] I have read the [Contributing Guidelines](https://github.com/IAmTamal/Milan/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (blank for no)

**Comment by tejaskh3** [comment]
I want to work on this issue. Also Can I add "How to set up razorpay keys and setup" raising another issue?

**Comment by IAmTamal** [comment]
Awesome, I think the variables changed accidentally when I was messing with the payment gateway in [this commit](https://github.com/IAmTamal/Milan/commit/84b0a2dcc372d74b35d4cba5e865be365541f11b) .

Also instead of another issue, you can do all the changes related to the Razorpay docs in this issue; make a PR once done !

**Comment by tejaskh3** [comment]
Done ✅
